name: workflow qui se dÃ©lcenche lors de la creation d'un fork

on:
  fork:

jobs:
  fork-message:
    runs-on: ubuntu-latest
    env:
      MESSAGE: "Merci d'avoir forkÃ© ce projet ! ðŸŽ‰"

    steps:
      - name: Afficher un message
        run: echo "$MESSAGE"
